---
- include_tasks: packages.yml
  tags: [ common, install, packages ]
- include_tasks: micro.yml
  when: ansible_distribution_version is version_compare('20.04', '<')
  tags: [ common, install, packages, micro ]
- include_tasks: editor.yml
  tags: [ common, editor ]
- include_tasks: timezone.yml
  tags: [ common, configure, timezone ]
- include_tasks: ntp.yml
  tags: [ common, ntp ]
- include_tasks: users.yml
  tags: [ common, users ]
