---
- include: packages.yml
  tags: [ common, install, packages ]
- include: micro.yml
  tags: [ common, install, packages, micro ]
- include: editor.yml
  tags: [ common, editor ]
- include: timezone.yml
  tags: [ common, configure, timezone ]
- include: ntp.yml
  tags: [ common, ntp ]
- include: users.yml
  tags: [ common, users ]
