---
# need for pass 'Install common packages'
- name: Ensure aptitude installed
  apt:
    name: aptitude
    state: present
  tags: [ common, packages ]

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  register: apt_cache
  tags: [ common, packages, upgrade ]

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ common_packages }}"
  tags: [ common, packages ]

- name: Install dev packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ common_packages_dev }}"
  tags: [ common, packages ]

# https://github.com/nicolargo/glances/issues/1033#issuecomment-279319763
- name: Upgrade pip and setuptools
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - setuptools
  tags: [ common, packages ]

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ common_packages_pip }}"
  tags: [ common, packages ]
