---
- name: Ensure aptitude installed
  apt: name=aptitude state=present
  tags: [ common, packages ]

- name: Update system packages
  apt:
        upgrade=safe
        update_cache=yes
        cache_valid_time=3600
  tags: [ common, packages ]

- name: Install common packages
  apt: name={{item}} state=latest
  with_items:
    - apt-transport-https
    - aptitude
    - curl
    - git
    - grc
    - htop
    - iotop
    - less
    - lnav
    - mc
    - mtr
    - ncdu
    - nmap
    - openssh-server
    - php5-cli
    - pv
    - python-setuptools
    - screen
    - sshfs
    - traceroute
    - tree
    - unzip
    - vim
    - vnstat
    - whois
    - zsh
  tags: [ common, packages ]

- name: Install dev packages
  apt: name={{item}} state=latest
  with_items:
    - build-essential
    - g++
    - ipython
    #- nodejs
    #- nodejs-dev
    - php5-cli
    - python-dev

    - libxml2-dev # for howdoi
    - libxslt1-dev # for howdoi
    - zlib1g-dev # for howdoi

    #- tig
    #- tmux
  tags: [ common, packages ]

- name: Install easy_install pip
  easy_install: name=pip
  tags: [ common, packages ]

- name: Install pip packages
  pip: name={{ item }} state=latest
  with_items:
    #- fpp # https://github.com/facebook/PathPicker
    - glances # https://github.com/nicolargo/glances
    - howdoi # requires libxml2-dev libxslt-dev packages
    - httpie # https://github.com/jkbrzt/httpie
    - percol # https://github.com/mooz/percol
  tags: [ common, packages ]
