---
- name: Ensure aptitude installed
  apt: name=aptitude state=present
  tags: [ common, packages ]

- name: Update apt cache
  apt:
        update_cache=yes
        cache_valid_time=3600
  register: apt_cache
  tags: [ common, packages, upgrade ]

# TODO: move to role upgrade
#- name: Update system packages
#  apt:  upgrade=yes
#  when: apt_cache.changed
#  tags: [ common, packages, upgrade ]

- name: Install common packages
  apt: name={{item}} state=present
  with_items:
    - apt-transport-https
    - aptitude
    - curl
    - git
    - grc
    - htop
    - idn
    - imagemagick
    - iotop
    - less
    - lnav
    - mc
    - mtr
    - ncdu
    - nmap
    - openssh-server
    #- php5-cli
    - pv
    - python-setuptools
    - screen
    - sshfs
    - traceroute
    - tree
    - tmux
    - unzip
    - vim-gtk # invludes more compiled modules, + 28 mb
    - vnstat
    - whois
    - zsh
  tags: [ common, packages ]

- name: Install dev packages
  apt: name={{item}} state=present
  with_items:
    #- build-essential
    #- g++
    #- ipython
    #- nodejs
    #- nodejs-dev
    #- php5-cli
    - python-dev

    #- libxml2-dev # for howdoi
    #- libxslt1-dev # for howdoi
    #- zlib1g-dev # for howdoi

    #- tig
    #- tmux
  tags: [ common, packages ]

- name: Install easy_install pip
  easy_install: name=pip
  tags: [ common, packages ]

- name: Install pip packages
  pip: name={{ item }} state=present
  with_items:
    #- fpp # https://github.com/facebook/PathPicker
    - glances # https://github.com/nicolargo/glances
    #- howdoi # requires libxml2-dev libxslt-dev packages
    - httpie # https://github.com/jkbrzt/httpie
    - mycli # https://github.com/dbcli/mycli
    - percol # https://github.com/mooz/percol
    - powerline-status
    - ps_mem # https://github.com/pixelb/ps_mem
    #- watchdog # watchmedo, https://github.com/gorakhargosh/watchdog
  tags: [ common, packages ]
