---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  register: apt_cache
  tags: [ common, packages, upgrade ]

# need for pass 'Install common packages'
#- name: Ensure aptitude installed
#  apt:
#    name: aptitude
#    state: present

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present

- name: Install dev packages
  apt:
    name: "{{ common_packages_dev }}"
    state: present

- name: Use python3 by default
  alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/bin/python

# https://github.com/nicolargo/glances/issues/1033#issuecomment-279319763
- name: Upgrade pip and setuptools
  pip:
    name:
      - pip
      - setuptools
    state: latest
    # executable: /usr/bin/pip3
  changed_when: false
  tags: skip_ansible_lint
  when: ansible_distribution_version is version_compare('24.04', '<') # externally-managed-environment

- name: Install pip packages
  pip:
    name: "{{ common_packages_pip }}"
    state: present
  when: ansible_distribution_version is version_compare('24.04', '<') # externally-managed-environment
